runcmd:
- rm -f /etc/update-motd.d/*
- rm -f /etc/legal
- ln -s /home/wizard/puzzle.txt /etc/motd
- sudo chown -R 1000:1000 /home/wizard
users:
- name: wizard
  shell: /bin/bash
  ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC9wSyYtapHqZCe/HjTICp5fVXLcEZhrkQt3NJuahGdpBKi5ONzEHzSArPGQOnu6uJ0SkRZ/U6voVakjft3Ev+qGe+MCfRyTSYbksU4wg5JbaMmtjUxnv7IlhZIXmp6gGu9yXNmuBocycuVnaUGTtpXxy3g2fADv292gobk8dz1pSryjoyo0xW7RiCiyUsgktVLb4eMHIIfeU0/UbjJFfuqSWCGnZk9speQ6/HeLzqmVL1RPu2vaGvRWTJeEwQmvWBD/0OYUd/8fMrDQFEFfCl2fegD5k6hJV4iwX9/AQHcvjrs0mZyhE7X/hCxzlr7CMrI7nub2727zd8jyrcFwkjHtR8F/jxyfg7V/qO6JqZoUAcOBBAsbS+uh3gnz08GctXjQMNOgRf0J6rz8eHTx+rB0tNYGgXQ3k17MumUWoDTLz57cijegfS6zXROUvTeLefd/7Ta/aNmegO4KfyaJTLJr2YJ7qEiT60xgvt+yPngWU9wZhwzQt1wmnlmiyZUeP0= wizard@wizard
  sudo: ALL=(ALL) NOPASSWD:ALL
write_files:
- content: |
    export TERM=xterm-256color
    alias ls='ls --color'
  path: /home/wizard/.bash_profile
  permissions: 0644
- content: |
    import sys
    from pathlib import Path
    p = Path('/var/lib/cloud/data/result.json')
    if not p.exists():
        print("result.json doesn't exist yet")
        sys.exit(1)
    contents = p.read_text()
    if '"errors": []' not in contents:
        print("cloud-init failed")
        print(contents)
        sys.exit(1)
    print("Started!")
  path: /home/wizard/setup/started_up.py
  permissions: 0777
- content: ""
  path: /etc/legal
  permissions: 0644


