version: "3.3"
services:
  db:
    image: postgres
    volumes:
      - /postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  goproxy:
    # todo: use a smaller image at some point, we don't really need ubuntu here
    image: ubuntu
    command: /app/go_proxy/server
    volumes:
      - .:/app
  rails:
    build: docker/rails
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    envfile: secrets.sh
    volumes:
      - .:/app
  web:
    build: docker/nginx
    ports:
      - "80:80"
