version: "3.3"
services:
  db:
    image: postgres
    volumes:
      - ~/work/.exploding_computers_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  goproxy:
    # todo: use a smaller image at some point, we don't really need ubuntu here
    image: ubuntu
    command: /app/go_proxy/server
    volumes:
      - .:/app
  rails:
    build: 
        dockerfile: docker/rails/Dockerfile
        context: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file: secrets.sh
    volumes:
      - .:/app
  web:
    build:
        dockerfile: docker/nginx/Dockerfile
        context: .
    ports:
      - "8777:80"
