version: "3.3"
networks:
  ignitenet:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.61.0.1/16
    driver_opts:
      com.docker.network.bridge.name: ignite0
services:
  db:
    image: postgres
    volumes:
      - ~/work/.exploding_computers_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  goproxy:
    # todo: use a smaller image at some point, we don't really need ubuntu here
    image: ghcr.io/jvns/exploding-computers/goproxy
    build:
        dockerfile: $PWD/docker/goproxy/Dockerfile
        context: multi-gotty
    command: /usr/bin/multi-gotty --ws-origin https://exploding-puzzles-test.ngrok.io --index-dir /app/gotty-statics/ --port 8080 --address 0.0.0.0 http://rails:3000/sessions
    volumes:
      - .:/app
    networks:
        - default
        - ignitenet
  rails:
    image: ghcr.io/jvns/exploding-computers/rails
    build: 
        dockerfile: docker/rails/Dockerfile
        context: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file: secrets.sh
    networks:
        - default
        - ignitenet
    volumes:
      - .:/app
    extra_hosts:
        - host:192.168.1.181
  web:
    image: ghcr.io/jvns/exploding-computers/web
    build:
        dockerfile: docker/nginx/Dockerfile
        context: .
    volumes:
      - ./public:/app/public
    ports:
      - "8777:80"
