version: "3.3"
services:
  db:
    image: postgres
    volumes:
      - /postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  goproxy:
    # todo: use a smaller image at some point, we don't really need ubuntu here
    image: ghcr.io/jvns/exploding-computers/goproxy
    build:
        dockerfile: $PWD/docker/goproxy/Dockerfile
        context: multi-gotty
    command: /usr/bin/multi-gotty --ws-origin https://exploding-computers.jvns.ca --index-dir /app/gotty-statics/ --port 8080 --address 0.0.0.0 http://rails:3000/sessions
    volumes:
      - .:/app
  rails:
    build: 
        dockerfile: docker/rails/Dockerfile
        context: .
    image: ghcr.io/jvns/exploding-computers/rails
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file: secrets_prod.sh
    volumes:
      - .:/app
  web:
    build:
        dockerfile: docker/nginx/Dockerfile
        context: .
    image: ghcr.io/jvns/exploding-computers/web
    volumes:
      - ./public:/app/public
    ports:
      - "80:80"
