# fly.toml file generated for exploding-rails on 2021-02-02T20:05:42-05:00

app = "exploding-rails"

kill_signal = "SIGINT"
kill_timeout = 5

[experimental]
  private_network=true

[env]
  RAILS_ENV = "production"
  RAILS_LOG_TO_STDOUT = "1"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "10s"
    port = "3000"
    restart_limit = 5
    timeout = "2s"
