#cloud-config
packages:
- apache2
runcmd:
- rm -f /etc/update-motd.d/*
- rm -f /etc/legal
- ln -s /home/wizard/puzzle.txt /etc/motd
users:
- name: wizard
  shell: /bin/bash
  ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC9wSyYtapHqZCe/HjTICp5fVXLcEZhrkQt3NJuahGdpBKi5ONzEHzSArPGQOnu6uJ0SkRZ/U6voVakjft3Ev+qGe+MCfRyTSYbksU4wg5JbaMmtjUxnv7IlhZIXmp6gGu9yXNmuBocycuVnaUGTtpXxy3g2fADv292gobk8dz1pSryjoyo0xW7RiCiyUsgktVLb4eMHIIfeU0/UbjJFfuqSWCGnZk9speQ6/HeLzqmVL1RPu2vaGvRWTJeEwQmvWBD/0OYUd/8fMrDQFEFfCl2fegD5k6hJV4iwX9/AQHcvjrs0mZyhE7X/hCxzlr7CMrI7nub2727zd8jyrcFwkjHtR8F/jxyfg7V/qO6JqZoUAcOBBAsbS+uh3gnz08GctXjQMNOgRf0J6rz8eHTx+rB0tNYGgXQ3k17MumUWoDTLz57cijegfS6zXROUvTeLefd/7Ta/aNmegO4KfyaJTLJr2YJ7qEiT60xgvt+yPngWU9wZhwzQt1wmnlmiyZUeP0=
    wizard@wizard
  sudo: ALL=(ALL) NOPASSWD:ALL
write_files:
- content: |
    export TERM=xterm-256color
    alias ls='ls --color'
  path: /home/wizard/.bash_profile
  permissions: '0644'
- content: |
    #!/usr/bin/env python
    import sys
    from pathlib import Path
    p = Path('/var/lib/cloud/data/result.json')
    if not p.exists():
        print("result.json doesn't exist yet")
        sys.exit(1)
    contents = p.read_text()
    if '"errors": []' not in contents:
        print("cloud-init failed")
        print(contents)
        sys.exit(1)
    print("Started!")
  path: /usr/local/bin/started_up
  permissions: '0777'
- content: ''
  path: /etc/legal
  permissions: '0644'
- content: |
    #!/bin/bash
    set -e
    chown -R 1000:1000 /home/wizard
    cd /home/wizard
    sudo bash -x /home/wizard/setup/run.sh
    sleep 2
    rm -rf /home/wizard/setup
  path: /var/lib/cloud/scripts/per-boot/setup_puzzle
  permissions: '0777'
- content: |
    #!/bin/bash
    # idempotent
    set -e
    service apache2 start
    mkdir -p /var/www/html/a/b/c
    echo 'you got it! congratulations!' > /var/www/html/a/b/c/index.html
    chmod 000 /var/www/html/a/
  owner: root
  path: /home/wizard/setup/run.sh
  permissions: '0755'
- content: |
    Apache by default serves files from /var/www/html.
  owner: root
  path: /home/wizard/hints/hint1.txt
  permissions: '0444'
- content: |
    403 Forbidden is probably related to the file permissions somehow
  owner: root
  path: /home/wizard/hints/hint2.txt
  permissions: '0444'
- content: |2
                       ~~~~~~~~~~
                       greetings!
                       ~~~~~~~~~~
    Running:

    $ curl localhost/a/b/c/

    gives you a 403 Forbidden error. Why? Fix it.

    You have root access. You can't break anything important, so have fun!
    Good luck! Here's a terminal.
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  path: /home/wizard/puzzle.txt
  permissions: 0644
