#cloud-config
packages:
- apache2
runcmd:
- rm -f /etc/update-motd.d/*
users:
- name: wizard
  shell: /bin/bash
  ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC9wSyYtapHqZCe/HjTICp5fVXLcEZhrkQt3NJuahGdpBKi5ONzEHzSArPGQOnu6uJ0SkRZ/U6voVakjft3Ev+qGe+MCfRyTSYbksU4wg5JbaMmtjUxnv7IlhZIXmp6gGu9yXNmuBocycuVnaUGTtpXxy3g2fADv292gobk8dz1pSryjoyo0xW7RiCiyUsgktVLb4eMHIIfeU0/UbjJFfuqSWCGnZk9speQ6/HeLzqmVL1RPu2vaGvRWTJeEwQmvWBD/0OYUd/8fMrDQFEFfCl2fegD5k6hJV4iwX9/AQHcvjrs0mZyhE7X/hCxzlr7CMrI7nub2727zd8jyrcFwkjHtR8F/jxyfg7V/qO6JqZoUAcOBBAsbS+uh3gnz08GctXjQMNOgRf0J6rz8eHTx+rB0tNYGgXQ3k17MumUWoDTLz57cijegfS6zXROUvTeLefd/7Ta/aNmegO4KfyaJTLJr2YJ7qEiT60xgvt+yPngWU9wZhwzQt1wmnlmiyZUeP0= wizard@wizard
  sudo: ALL=(ALL) NOPASSWD:ALL
  uid: 02471
write_files:
- content: |
    export TERM=xterm-256color
    alias ls='ls --color'
  path: /home/wizard/.bash_profile
  permissions: 0644
- content: |
    #!/bin/bash
    mkdir -p /var/www/html/a/b/c
    echo 'you got it! congratulations!' > /var/www/html/a/b/c/index.html
    chmod 000 /var/www/html/a/
  owner: root
  path: /home/wizard/files/run.sh
  permissions: 0755
- content: |2
                       ~~~~~~~~~~
                       greetings!
                       ~~~~~~~~~~
    Running:

    $ curl localhost/a/b/c/

    gives you a 403 Forbidden error. Why? Fix it.

    You have root access. You can't break anything important, so have fun!
    Good luck! Here's a terminal.
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  owner: root
  path: /etc/motd
  permissions: 0644
- content: |2
                       ~~~~~~~~~~
                       greetings!
                       ~~~~~~~~~~
    Running:

    $ curl localhost/a/b/c/

    gives you a 403 Forbidden error. Why? Fix it.

    You have root access. You can't break anything important, so have fun!
    Good luck! Here's a terminal.
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  owner: root
  path: /home/wizard/puzzle.txt
  permissions: 0644
- content: |
    Apache by default serves files from /var/www/html.
  owner: root
  path: /home/wizard/hints/hint1.txt
  permissions: 0444
- content: |
    403 Forbidden is probably related to the file permissions somehow
  owner: root
  path: /home/wizard/hints/hint2.txt
  permissions: 0444
- content: ""
  path: /etc/legal
  permissions: 0644
