#cloud-config
packages:
- acl
write_files:
- content: |
    #!/bin/bash
    cd /home/wizard
    chown root:root read-me.txt
    setfacl -m "u:wizard:---" read-me.txt
  owner: root
  path: /home/wizard/setup/run.sh
  permissions: '0755'
- content: |2
                       ~~~~~~~~~~
                       greetings!
                       ~~~~~~~~~~

    There's a file called `read-me.txt`. Fix its permissions so it can be read by the user `wizard` (your user). Rules:
    1. You can fix the permissions as root, but you have to read the file as the wizard user.
    2. You can't change the owner of the file

    You have root access. You can't break anything important, so have fun!
    Good luck! Here's a terminal.
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  owner: root
  path: /home/wizard/puzzle.txt
  permissions: '0644'
- content: |
    you read me! yay!
  path: /home/wizard/read-me.txt
  permissions: '0644'
- content: |
    When you ls -l read-me.txt, there's a + sign. Why?
  path: /home/wizard/hints/hint1.txt
  permissions: '0444'
- content: |
    Run `getfacl read-me.txt` and figure out what it means.
  path: /home/wizard/hints/hint2.txt
  permissions: '0444'
