#!/bin/bash
set -eu

GIT_DIR="/git/incident-service.git"
TARGET="/app"

while read oldrev newrev ref; do
  # We gonna do stuff.
  BRANCH=$(git rev-parse --symbolic --abbrev-ref $ref)

  if [[ $BRANCH == "main" ]]; then
    # Send a nice message to the machine pushing to this remote repository.
    mkdir -p $TARGET
    cd $TARGET
    echo "Push received! Deploying branch: ${BRANCH}..."

    # "Deploy" the branch we just pushed to a specific directory.
    git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f $BRANCH
    #chown -R rails:rails /home/wizard-debugging-school-deployed/
  else
    echo "Not main branch. Skipping."
    return 0
  fi

  docker-compose -f docker-compose-prod.yml pull && docker-compose -f docker-compose-prod.yml up --no-build -d
  go build
  service ignite-manager restart
  echo "Done"
done

