name: "Cleanup old VMs"
on:
  push:
  schedule:
  - cron: "*/2 * * * *"

jobs:
  cleanup-old-vms:
    runs-on: ubuntu-latest
    steps:
    - name: "Cleanup old sessions"
      run: |
        curl https://exploding-rails.fly.dev/sessions/cleanup
