name: "Cleanup old VMs"
on:
  push:
  schedule:
  - cron: "* * * * *"

jobs:
  delete-old-vms:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Install fly and jq"
      run: |
        mkdir bin
        wget -nv -O bin/flyctl https://github.com/superfly/flyctl/releases/download/v0.0.173/flyctl_0.0.173_Linux_x86_64
        wget -nv -O bin/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
        chmod 755 bin/*
        echo "$PWD/bin" >> $GITHUB_PATH
    - name: "Cleanup VMs"
      env: 
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      run: bash scripts/cleanup_old_vms.sh
