name: Publish Docker image
on: [push]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make fake secrets file
        run: touch /home/runner/work/incident-service/incident-service/secrets_prod.sh
      - name: build docker containers
        run: docker-compose -f docker-compose-prod.yml build
